name: Publish NPM Package

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the 'main' branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Ensure Node.js version is 20 or higher
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use the secret we added to authenticate with NPM
      run: npm publish

    - name: Post-publish cleanup
      run: echo "Package published successfully!"
